name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: get node version
        id: node-version
        run: |
          echo node_version=$(cat .tool-versions | grep node | cut -d' ' -f2) >> $GITHUB_OUTPUT

      - name: get pnpm version
        id: pnpm-version
        run: |
          echo pnpm_version=$(cat .tool-versions | grep pnpm | cut -d' ' -f2) >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.node-version.outputs.node_version }}

      - name: Install pnpm
        run: |
          npm install -g pnpm@${{ steps.pnpm-version.outputs.pnpm_version }}

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Run lint
        run: |
          pnpm lint

      - name: Type check
        run: |
          npx tsc --noEmit
